apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.org/rewrites: "serviceName=server-cluster-ip-service rewrite=/;"
    # TODO: Only needed for production deployment
    # certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    # nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  # TODO: Only needed for production deployment
  # tls:
  #   - hosts:
  #       - <domain name>
  #       - www.<domain name>
  #     secretName: k8s-multi-com
  rules:
      - http:
          paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: server-cluster-ip-service
                port: 
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-cluster-ip-service
                port: 
                  number: 3000
        # host: <domain-name> # TODO: Only needed for Production
      - http:
          paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: server-cluster-ip-service
                port: 
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-cluster-ip-service
                port: 
                  number: 3000
        # Here we are adding www because www.<domain> and <domain> are treated as different thus rules will not be applied in one of the case
        # host: www.<domain-name> # TODO: Only needed for Production
